<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

	<!-- generator="WordPress/6.1.1" created="2023-02-02 07:47" -->
	<textarea name="content" cols="77" rows="30">
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>
	<channel>
		<title></title>
		<link>https://techstream.org</link>
		<description>Techstream</description>
		<pubDate>Thu, 02 Feb 2023 07:47:51 +0000</pubDate>
		<language>en-US</language>
		<wp:wxr_version>1.2</wp:wxr_version>
		<wp:base_site_url>https://techstream.org</wp:base_site_url>
		<wp:base_blog_url>https://techstream.org</wp:base_blog_url>
		<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[anush]]></wp:author_login><wp:author_email><![CDATA[anush@techstream.org]]></wp:author_email><wp:author_display_name><![CDATA[Anush]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
		<generator>https://wordpress.org/?v=6.1.1</generator>
		<?php 
			for ( $i = 0; $i<sizeof($data['items']); $i++ ) {
		?>
			<item>
				<title><![CDATA[<?=$data['items'][$i]['TITLE']?>]]></title>
				<link><?=PUBLICPATH . $data['items'][$i]['LINK']?></link>
				<pubDate><?php if ( $data['items'][$i]['DATE'] != '0000-00-00 00:00:00') : ?><?=$data['items'][$i]['DATE']?><?php else : ?> value="<?=date("Y-m-d  H:i:s",time())?><?php endif; ?> +0000</pubDate>
				<dc:creator>
					<![CDATA[admin]]>
				</dc:creator>
				<description><?=$data['items'][$i]['DES']?></description>
				<wp:post_type><![CDATA[post]]></wp:post_type>
				<content:encoded>
					<![CDATA[<?=htmlspecialchars_decode($data['items'][$i]['CONTENT'])?>:]]>
				</content:encoded>
				<wp:post_id><?=$data['items'][$i]['ID']?></wp:post_id>
				<wp:post_date>
					<![CDATA[<?php if ( $data['items'][$i]['DATE'] != '0000-00-00 00:00:00') : ?> value="<?=$data['items'][$i]['DATE']?>" <?php else : ?> value="<?=date("Y-m-d  H:i:s",time())?>" <?php endif; ?>]]>
				</wp:post_date>
				<wp:comment_status>
					<![CDATA[closed]]>
				</wp:comment_status>
				<wp:ping_status>
					<![CDATA[closed]]>
				</wp:ping_status>
				<wp:post_name>
					<![CDATA[<?=$data['LINK']?>]]>
				</wp:post_name>
				<wp:status>
					<![CDATA[publish]]>
				</wp:status>
				<wp:is_sticky>0</wp:is_sticky>
				<category domain="category" nicename="<?=($data['items'][$i]['SECURL'])?>">
					<![CDATA[<?=removeHyphen($data['items'][$i]['SECURL'])?>]]>
				</category>
			</item>
		<?php
			}
		?>
	</channel>
</rss>
</textarea>
	